
name: Testes

# Gatilhos
#   Programados
#   Acionados
on:
  push:
    branches: [ main ]

jobs:
  build:

# Qual a máquina ou ambiente que irá executar os testes
    runs-on: ubuntu-latest

# Passos
    steps:

# Download do código
    - uses: actions/checkout@v2

# Setup da versão do Node
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    
    - run: npm install
    - run: npm run cy:run
      continue-on-error: true

    - run: npm run report:merge
    - run: npm run report:mocha
    
# Github Pages -> publicar o relatório
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: mochawesome-report
